displayName=Shortest Grave
author=FIrgolitsch
description=Plan a route to your most recent demise
tags=shortest-path, grave, death, route
version=1.0.0
plugins=shortest-grave.ShortestGrave
build=standard