displayName=Shortest Grave
author=FIrgolitsch
description=Plan a route to your most recent demise
tags=pathfinder,map,waypoint,navigation,tileman,tilebound,closest,quickest,grave,gravestone,death,respawn
version=1.0.0
plugins=shortest-grave.ShortestGrave
build=standard